//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aGrader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aGrader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION: Compare files.
        /// </summary>
        internal static string ActionCompareFiles {
            get {
                return ResourceManager.GetString("ActionCompareFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION: Load outputs from file.
        /// </summary>
        internal static string ActionLoadOutputsFromTextFile {
            get {
                return ResourceManager.GetString("ActionLoadOutputsFromTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION: Repeat last action.
        /// </summary>
        internal static string ActionRepeatLast {
            get {
                return ResourceManager.GetString("ActionRepeatLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last action could not be repeated..
        /// </summary>
        internal static string ActionRepeatLast_LastActionCouldNotBeRepeated {
            get {
                return ResourceManager.GetString("ActionRepeatLast_LastActionCouldNotBeRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to repeat..
        /// </summary>
        internal static string ActionRepeatLast_NothingToRepeat {
            get {
                return ResourceManager.GetString("ActionRepeatLast_NothingToRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compile the source code..
        /// </summary>
        internal static string CannotCompile {
            get {
                return ResourceManager.GetString("CannotCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading file {0}..
        /// </summary>
        internal static string CouldNotLoadFile {
            get {
                return ResourceManager.GetString("CouldNotLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory does not exist..
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected output.
        /// </summary>
        internal static string ExpectedOutput {
            get {
                return ResourceManager.GetString("ExpectedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text file (*.txt) | *.txt.
        /// </summary>
        internal static string FileFilter_TXT {
            get {
                return ResourceManager.GetString("FileFilter_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        internal static string FileFilter_XML {
            get {
                return ResourceManager.GetString("FileFilter_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT: Number.
        /// </summary>
        internal static string InputNumber {
            get {
                return ResourceManager.GetString("InputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input/Output.
        /// </summary>
        internal static string InputOutput {
            get {
                return ResourceManager.GetString("InputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT: Random number.
        /// </summary>
        internal static string InputRandomNumber {
            get {
                return ResourceManager.GetString("InputRandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX can&apos;t be greater than Min.
        /// </summary>
        internal static string InputRandomNumber_MaxCantBeGreatherThanMin {
            get {
                return ResourceManager.GetString("InputRandomNumber_MaxCantBeGreatherThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN can&apos;t be greater than Max.
        /// </summary>
        internal static string InputRandomNumber_MinCantBeGreatherThanMax {
            get {
                return ResourceManager.GetString("InputRandomNumber_MinCantBeGreatherThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT: Text.
        /// </summary>
        internal static string InputString {
            get {
                return ResourceManager.GetString("InputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT: Text file.
        /// </summary>
        internal static string InputTextFile {
            get {
                return ResourceManager.GetString("InputTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION: comparison of file {0} and generated file.
        /// </summary>
        internal static string IOFDescription_CompareFiles {
            get {
                return ResourceManager.GetString("IOFDescription_CompareFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT: number {0}.
        /// </summary>
        internal static string IOFDescription_InputNumber {
            get {
                return ResourceManager.GetString("IOFDescription_InputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT: random decimal number from {0} to {1}.
        /// </summary>
        internal static string IOFDescription_InputRandomDecimalNumber {
            get {
                return ResourceManager.GetString("IOFDescription_InputRandomDecimalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT: random number from {0} to {1}.
        /// </summary>
        internal static string IOFDescription_InputRandomNumber {
            get {
                return ResourceManager.GetString("IOFDescription_InputRandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT: text: \&quot;{0}\&quot;.
        /// </summary>
        internal static string IOFDescription_InputString {
            get {
                return ResourceManager.GetString("IOFDescription_InputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT: file {0}.
        /// </summary>
        internal static string IOFDescription_InputTextFile {
            get {
                return ResourceManager.GetString("IOFDescription_InputTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION: Load outputs from file.
        /// </summary>
        internal static string IOFDescription_LoadOutputsFromFile {
            get {
                return ResourceManager.GetString("IOFDescription_LoadOutputsFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: Number based on generated values..
        /// </summary>
        internal static string IOFDescription_NumberBasedOnGeneratedInput {
            get {
                return ResourceManager.GetString("IOFDescription_NumberBasedOnGeneratedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: Number satisfying {0} conditions..
        /// </summary>
        internal static string IOFDescription_NumberSatisfyingMultipleConditions {
            get {
                return ResourceManager.GetString("IOFDescription_NumberSatisfyingMultipleConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: Number satisfying 1 condition..
        /// </summary>
        internal static string IOFDescription_NumberSatisfyingSingleCondition {
            get {
                return ResourceManager.GetString("IOFDescription_NumberSatisfyingSingleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: Number {0}.
        /// </summary>
        internal static string IOFDescription_OutputNumber {
            get {
                return ResourceManager.GetString("IOFDescription_OutputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: text: \&quot;{0}\&quot;.
        /// </summary>
        internal static string IOFDescription_OutputString {
            get {
                return ResourceManager.GetString("IOFDescription_OutputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS: Prohibited command  \&quot;{0}\&quot;.
        /// </summary>
        internal static string IOFDescription_ProhibitedCommand {
            get {
                return ResourceManager.GetString("IOFDescription_ProhibitedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION: repeat last step {0}x.
        /// </summary>
        internal static string IOFDescription_RepeatLast {
            get {
                return ResourceManager.GetString("IOFDescription_RepeatLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS: Requied command  \&quot;{0}\&quot;.
        /// </summary>
        internal static string IOFDescription_RequiedCommand {
            get {
                return ResourceManager.GetString("IOFDescription_RequiedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS: Maximal deviation {0}.
        /// </summary>
        internal static string IOFDescription_SettingsDeviation {
            get {
                return ResourceManager.GetString("IOFDescription_SettingsDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS: Program timeout: {0}.
        /// </summary>
        internal static string IOFDescription_SettingsTimeout {
            get {
                return ResourceManager.GetString("IOFDescription_SettingsTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS: Startup arguments:  \&quot;{0}\&quot;.
        /// </summary>
        internal static string IOFDescription_StartupArguments {
            get {
                return ResourceManager.GetString("IOFDescription_StartupArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: count of number matching {0} conditions.
        /// </summary>
        internal static string IOFDesruption_CountOfNumMatchingMultipleConditions {
            get {
                return ResourceManager.GetString("IOFDesruption_CountOfNumMatchingMultipleConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: count of number matching 1 condition.
        /// </summary>
        internal static string IOFDesruption_CountOfNumMatchingSingleCondition {
            get {
                return ResourceManager.GetString("IOFDesruption_CountOfNumMatchingSingleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory that contains directories which contains &quot;*.java&quot; files (one directory = one test).
        /// </summary>
        internal static string LanguageSelection_ChooseFolderJavaMultiFiles {
            get {
                return ResourceManager.GetString("LanguageSelection_ChooseFolderJavaMultiFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory that contains individual files with &quot;*.java&quot; extension (one file = one test).
        /// </summary>
        internal static string LanguageSelection_ChooseFolderSingleJava {
            get {
                return ResourceManager.GetString("LanguageSelection_ChooseFolderSingleJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory that contains files with &quot;*.c&quot; extension..
        /// </summary>
        internal static string LanguageSelection_ChoseCFiles {
            get {
                return ResourceManager.GetString("LanguageSelection_ChoseCFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tests were finished..
        /// </summary>
        internal static string MainForm_AllTestsWereFinnished {
            get {
                return ResourceManager.GetString("MainForm_AllTestsWereFinnished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not opened.
        ///List of files will be refreshed now..
        /// </summary>
        internal static string MainForm_CannotOpenFile {
            get {
                return ResourceManager.GetString("MainForm_CannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested generated numbers no longer cannot be used..
        /// </summary>
        internal static string MainForm_CantUseRequestedGeneratedNumbers {
            get {
                return ResourceManager.GetString("MainForm_CantUseRequestedGeneratedNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating a file {0}..
        /// </summary>
        internal static string MainForm_CouldNotCreateTextFile {
            get {
                return ResourceManager.GetString("MainForm_CouldNotCreateTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} was tested successully!.
        /// </summary>
        internal static string MainForm_FileWasSuccessfulyTested {
            get {
                return ResourceManager.GetString("MainForm_FileWasSuccessfulyTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing inputs/outputs will be overwriten..
        /// </summary>
        internal static string MainForm_InputsAndOutputsWillBeOverwriten {
            get {
                return ResourceManager.GetString("MainForm_InputsAndOutputsWillBeOverwriten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no source codes in the selected directory!.
        /// </summary>
        internal static string MainForm_NoSourceCodesInSelectedDirectory {
            get {
                return ResourceManager.GetString("MainForm_NoSourceCodesInSelectedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to export. You have to add some Input/Output to the protocol first..
        /// </summary>
        internal static string MainForm_NothingToExport {
            get {
                return ResourceManager.GetString("MainForm_NothingToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of files: {0}.
        /// </summary>
        internal static string MainForm_NumberOfFiles {
            get {
                return ResourceManager.GetString("MainForm_NumberOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting tests!.
        /// </summary>
        internal static string MainForm_StartingTests {
            get {
                return ResourceManager.GetString("MainForm_StartingTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct: {0} | Incorrect: {1} | Time: {2}| {3}.
        /// </summary>
        internal static string MainForm_TestResultLine {
            get {
                return ResourceManager.GetString("MainForm_TestResultLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a directory with source codes first..
        /// </summary>
        internal static string MainForm_YouHaveToSelectDirectoryWithSourceCodes {
            get {
                return ResourceManager.GetString("MainForm_YouHaveToSelectDirectoryWithSourceCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to create test protocol first..
        /// </summary>
        internal static string MainForm_YouNeedToCreateTestProtocolFirst {
            get {
                return ResourceManager.GetString("MainForm_YouNeedToCreateTestProtocolFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string NameOfFile {
            get {
                return ResourceManager.GetString("NameOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to repeat..
        /// </summary>
        internal static string NothingToRepeat {
            get {
                return ResourceManager.GetString("NothingToRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid files were found..
        /// </summary>
        internal static string NoValidFilesFound {
            get {
                return ResourceManager.GetString("NoValidFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: Count of numbers matching conditions.
        /// </summary>
        internal static string OutputCountOfNumbersMatchingConditions {
            get {
                return ResourceManager.GetString("OutputCountOfNumbersMatchingConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition is not valid..
        /// </summary>
        internal static string OutputCountOfNumbersMatchingConditions_InvalidCondition {
            get {
                return ResourceManager.GetString("OutputCountOfNumbersMatchingConditions_InvalidCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested count of numbers is not possible..
        /// </summary>
        internal static string OutputCountOfNumbersMatchingConditions_RequestedNumberOfNumbersIsNotPOssible {
            get {
                return ResourceManager.GetString("OutputCountOfNumbersMatchingConditions_RequestedNumberOfNumbersIsNotPOssible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This condition already exists..
        /// </summary>
        internal static string OutputCountOfNumbersMatchingConditions_ThisConditionAllreadyExists {
            get {
                return ResourceManager.GetString("OutputCountOfNumbersMatchingConditions_ThisConditionAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select condition for deletion first..
        /// </summary>
        internal static string OutputCountOfNumbersMatchingConditions_YouHaveToSelectConditionForDeletion {
            get {
                return ResourceManager.GetString("OutputCountOfNumbersMatchingConditions_YouHaveToSelectConditionForDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: Number.
        /// </summary>
        internal static string OutputNumber {
            get {
                return ResourceManager.GetString("OutputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: Number based on generated number.
        /// </summary>
        internal static string OutputNumberBasedOnRandomInput {
            get {
                return ResourceManager.GetString("OutputNumberBasedOnRandomInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math has an incorrect format!
        ///If you still wish to continue then the object will be deleted..
        /// </summary>
        internal static string OutputNumberBasedOnRandomInput_InvalidFormatOfMath {
            get {
                return ResourceManager.GetString("OutputNumberBasedOnRandomInput_InvalidFormatOfMath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter valid math..
        /// </summary>
        internal static string OutputNumberBasedOnRandomInput_YouHaveToEnterValidMath {
            get {
                return ResourceManager.GetString("OutputNumberBasedOnRandomInput_YouHaveToEnterValidMath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: Number matching conditions.
        /// </summary>
        internal static string OutputNumberMatchingConditions {
            get {
                return ResourceManager.GetString("OutputNumberMatchingConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This condition already exists..
        /// </summary>
        internal static string OutputNumberMatchingConditions_ThisConditionAllreadyExists {
            get {
                return ResourceManager.GetString("OutputNumberMatchingConditions_ThisConditionAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT: Text.
        /// </summary>
        internal static string OutputString {
            get {
                return ResourceManager.GetString("OutputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS: Deviation.
        /// </summary>
        internal static string SettingsDeviation {
            get {
                return ResourceManager.GetString("SettingsDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation is already set!.
        /// </summary>
        internal static string SettingsDeviation_DeviationIsAllreadySet {
            get {
                return ResourceManager.GetString("SettingsDeviation_DeviationIsAllreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS: Prohibited command.
        /// </summary>
        internal static string SettingsProhibitedCommand {
            get {
                return ResourceManager.GetString("SettingsProhibitedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS: Required command.
        /// </summary>
        internal static string SettingsRequiedCommand {
            get {
                return ResourceManager.GetString("SettingsRequiedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS: Startup arguments.
        /// </summary>
        internal static string SettingsStartupArguments {
            get {
                return ResourceManager.GetString("SettingsStartupArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup arguments are already set..
        /// </summary>
        internal static string SettingsStartupArguments_StartupArgumentsAreAllreadySet {
            get {
                return ResourceManager.GetString("SettingsStartupArguments_StartupArgumentsAreAllreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS: Program timeout.
        /// </summary>
        internal static string SettingsTimeout {
            get {
                return ResourceManager.GetString("SettingsTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout is already set!.
        /// </summary>
        internal static string SettingsTimeout_TimeoutAllreadySet {
            get {
                return ResourceManager.GetString("SettingsTimeout_TimeoutAllreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files with main method found!.
        /// </summary>
        internal static string SourceCodeJava_MultipleFilesWithMainFound {
            get {
                return ResourceManager.GetString("SourceCodeJava_MultipleFilesWithMainFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file with main method found!.
        /// </summary>
        internal static string SourceCodeJava_NoFileWithMainFound {
            get {
                return ResourceManager.GetString("SourceCodeJava_NoFileWithMainFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory contains programs made from single java file and programs with multiple java files  simultaneously.
        ///You have to choose only one of those..
        /// </summary>
        internal static string SourceCodes_JavaSingleMultiMismatch {
            get {
                return ResourceManager.GetString("SourceCodes_JavaSingleMultiMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type of file..
        /// </summary>
        internal static string SourceCodes_UnsuportedFileExtension {
            get {
                return ResourceManager.GetString("SourceCodes_UnsuportedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application was not terminated before timeout ({0}s)\n.
        /// </summary>
        internal static string Test_AppDidNotEndedBeforeTimeout {
            get {
                return ResourceManager.GetString("Test_AppDidNotEndedBeforeTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilator was not found! \n {0}.
        /// </summary>
        internal static string Test_CompilatorNotFound {
            get {
                return ResourceManager.GetString("Test_CompilatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java was not found!\n{0}.
        /// </summary>
        internal static string Test_JavaNotFound {
            get {
                return ResourceManager.GetString("Test_JavaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibited command found: {0}.
        /// </summary>
        internal static string Test_ProhibitedCommandFound {
            get {
                return ResourceManager.GetString("Test_ProhibitedCommandFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required command was not found: {0}.
        /// </summary>
        internal static string Test_RequiedCommandWasNotFound {
            get {
                return ResourceManager.GetString("Test_RequiedCommandWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test in progress.
        /// </summary>
        internal static string TestInProgress {
            get {
                return ResourceManager.GetString("TestInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type of source file!.
        /// </summary>
        internal static string TestManager_UnsuportedTypeOfSourceCode {
            get {
                return ResourceManager.GetString("TestManager_UnsuportedTypeOfSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; could not be converted to number..
        /// </summary>
        internal static string TestResult_CannotConvertNumber {
            get {
                return ResourceManager.GetString("TestResult_CannotConvertNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math contains the unknown variable..
        /// </summary>
        internal static string Validator_UnknownVariable {
            get {
                return ResourceManager.GetString("Validator_UnknownVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed!.
        /// </summary>
        internal static string XmlManager_ExportFailed {
            get {
                return ResourceManager.GetString("XmlManager_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export was succesful..
        /// </summary>
        internal static string XmlManager_ExportWasSuccesful {
            get {
                return ResourceManager.GetString("XmlManager_ExportWasSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during import..
        /// </summary>
        internal static string XmlManager_ImportFailed {
            get {
                return ResourceManager.GetString("XmlManager_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported and was not imported..
        /// </summary>
        internal static string XmlManager_InvalidDataImportFail {
            get {
                return ResourceManager.GetString("XmlManager_InvalidDataImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected XML file is not supported..
        /// </summary>
        internal static string XmlManager_UnsuportedXmlFile {
            get {
                return ResourceManager.GetString("XmlManager_UnsuportedXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to read {0}!.
        /// </summary>
        internal static string YouDontHavePermisionsToReadFile {
            get {
                return ResourceManager.GetString("YouDontHavePermisionsToReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select some file!.
        /// </summary>
        internal static string YouHaveToSelectFile {
            get {
                return ResourceManager.GetString("YouHaveToSelectFile", resourceCulture);
            }
        }
    }
}
