//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aGrader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aGrader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKCE: porovnej soubory.
        /// </summary>
        internal static string ActionCompareFiles {
            get {
                return ResourceManager.GetString("ActionCompareFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKCE: načti výstupy ze souboru.
        /// </summary>
        internal static string ActionLoadOutputsFromTextFile {
            get {
                return ResourceManager.GetString("ActionLoadOutputsFromTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKCE: opakování poslední akce.
        /// </summary>
        internal static string ActionRepeatLast {
            get {
                return ResourceManager.GetString("ActionRepeatLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední akce nemůže být zopakována..
        /// </summary>
        internal static string ActionRepeatLast_LastActionCouldNotBeRepeated {
            get {
                return ResourceManager.GetString("ActionRepeatLast_LastActionCouldNotBeRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není co opakovat..
        /// </summary>
        internal static string ActionRepeatLast_NothingToRepeat {
            get {
                return ResourceManager.GetString("ActionRepeatLast_NothingToRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód nemůže být zkompilován!.
        /// </summary>
        internal static string CannotCompile {
            get {
                return ResourceManager.GetString("CannotCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} se nepodařilo načíst..
        /// </summary>
        internal static string CouldNotLoadFile {
            get {
                return ResourceManager.GetString("CouldNotLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresář neexistuje!.
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errory.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Očekávaný výstup.
        /// </summary>
        internal static string ExpectedOutput {
            get {
                return ResourceManager.GetString("ExpectedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} neexistuje..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textový soubor | *.txt.
        /// </summary>
        internal static string FileFilter_TXT {
            get {
                return ResourceManager.GetString("FileFilter_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML soubory (*.xml)|*.xml.
        /// </summary>
        internal static string FileFilter_XML {
            get {
                return ResourceManager.GetString("FileFilter_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vstup.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTUP: číslo.
        /// </summary>
        internal static string InputNumber {
            get {
                return ResourceManager.GetString("InputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vstup/Výstup.
        /// </summary>
        internal static string InputOutput {
            get {
                return ResourceManager.GetString("InputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTUP: náhodné číslo.
        /// </summary>
        internal static string InputRandomNumber {
            get {
                return ResourceManager.GetString("InputRandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX nemůže být menší než MIN!.
        /// </summary>
        internal static string InputRandomNumber_MaxCantBeBiggerThanMin {
            get {
                return ResourceManager.GetString("InputRandomNumber_MaxCantBeBiggerThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN nemůže být větší než MAX!.
        /// </summary>
        internal static string InputRandomNumber_MinCantBeGreatherThanMax {
            get {
                return ResourceManager.GetString("InputRandomNumber_MinCantBeGreatherThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTUP: text.
        /// </summary>
        internal static string InputString {
            get {
                return ResourceManager.GetString("InputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTUP: textový soubor.
        /// </summary>
        internal static string InputTextFile {
            get {
                return ResourceManager.GetString("InputTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKCE: porovnání souboru {0} a vygenerovaného souboru.
        /// </summary>
        internal static string IOFDescription_CompareFiles {
            get {
                return ResourceManager.GetString("IOFDescription_CompareFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTUP: číslo {0}.
        /// </summary>
        internal static string IOFDescription_InputNumber {
            get {
                return ResourceManager.GetString("IOFDescription_InputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTUP: náhodné desetinné číslo od {0} do {1}.
        /// </summary>
        internal static string IOFDescription_InputRandomDecimalNumber {
            get {
                return ResourceManager.GetString("IOFDescription_InputRandomDecimalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTUP: náhodné celé číslo od {0} do {1}.
        /// </summary>
        internal static string IOFDescription_InputRandomNumber {
            get {
                return ResourceManager.GetString("IOFDescription_InputRandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTUP: text: \&quot;{0}\&quot;.
        /// </summary>
        internal static string IOFDescription_InputString {
            get {
                return ResourceManager.GetString("IOFDescription_InputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTUP: soubor {0}.
        /// </summary>
        internal static string IOFDescription_InputTextFile {
            get {
                return ResourceManager.GetString("IOFDescription_InputTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKCE: Načti výstupy ze souboru..
        /// </summary>
        internal static string IOFDescription_LoadOutputsFromFile {
            get {
                return ResourceManager.GetString("IOFDescription_LoadOutputsFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: Číslo závyslé na vygenerovaných hodnotách..
        /// </summary>
        internal static string IOFDescription_NumberBasedOnGeneratedInput {
            get {
                return ResourceManager.GetString("IOFDescription_NumberBasedOnGeneratedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: číslo splňující {0} podmínek..
        /// </summary>
        internal static string IOFDescription_NumberSatisfyingMultipleConditions {
            get {
                return ResourceManager.GetString("IOFDescription_NumberSatisfyingMultipleConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: číslo splňující 1 podmínku..
        /// </summary>
        internal static string IOFDescription_NumberSatisfyingSingleCondition {
            get {
                return ResourceManager.GetString("IOFDescription_NumberSatisfyingSingleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: Číslo {0}.
        /// </summary>
        internal static string IOFDescription_OutputNumber {
            get {
                return ResourceManager.GetString("IOFDescription_OutputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: text: \&quot;{0}\&quot;.
        /// </summary>
        internal static string IOFDescription_OutputString {
            get {
                return ResourceManager.GetString("IOFDescription_OutputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakázaný příkaz {0}.
        /// </summary>
        internal static string IOFDescription_ProhibitedCommand {
            get {
                return ResourceManager.GetString("IOFDescription_ProhibitedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKCE: opakuj předešlý krok {0}x.
        /// </summary>
        internal static string IOFDescription_RepeatLast {
            get {
                return ResourceManager.GetString("IOFDescription_RepeatLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyžadovaný příkay {0}.
        /// </summary>
        internal static string IOFDescription_RequiedCommand {
            get {
                return ResourceManager.GetString("IOFDescription_RequiedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASTAVENÍ: maximální odchylka {0}.
        /// </summary>
        internal static string IOFDescription_SettingsDeviation {
            get {
                return ResourceManager.GetString("IOFDescription_SettingsDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximální doba pro běh programu: {0}.
        /// </summary>
        internal static string IOFDescription_SettingsTimeout {
            get {
                return ResourceManager.GetString("IOFDescription_SettingsTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASTAVENÍ: souštěcí parametry: \&quot;{0}\&quot;.
        /// </summary>
        internal static string IOFDescription_StartupArguments {
            get {
                return ResourceManager.GetString("IOFDescription_StartupArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: počet čísel splňující {0} podmínek..
        /// </summary>
        internal static string IOFDesruption_CountOfNumMatchingMultipleConditions {
            get {
                return ResourceManager.GetString("IOFDesruption_CountOfNumMatchingMultipleConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: počet čísel splňujících 1 podmínku..
        /// </summary>
        internal static string IOFDesruption_CountOfNumMatchingSingleCondition {
            get {
                return ResourceManager.GetString("IOFDesruption_CountOfNumMatchingSingleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte složku která obsahuje složky které obsahují soubory s příponou &quot;*.java&quot;   (jedna složka jeden test).
        /// </summary>
        internal static string LanguageSelection_ChooseFolderJavaMultiFiles {
            get {
                return ResourceManager.GetString("LanguageSelection_ChooseFolderJavaMultiFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Zvolte složku která obsahuje jednotlivé soubory s příponou &quot;*.java&quot; (jeden soubor jeden test).
        /// </summary>
        internal static string LanguageSelection_ChooseFolderSingleJava {
            get {
                return ResourceManager.GetString("LanguageSelection_ChooseFolderSingleJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte složku která obsahuje soubory s příponou .c.
        /// </summary>
        internal static string LanguageSelection_ChoseCFiles {
            get {
                return ResourceManager.GetString("LanguageSelection_ChoseCFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny testy byli dokončeny!.
        /// </summary>
        internal static string MainForm_AllTestsWereFinnished {
            get {
                return ResourceManager.GetString("MainForm_AllTestsWereFinnished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor se nepovedlo otevřít./nSeznam souborů bude nyní aktualizován..
        /// </summary>
        internal static string MainForm_CannotOpenFile {
            get {
                return ResourceManager.GetString("MainForm_CannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadovaná náhodná čísla nelze nadále použít!.
        /// </summary>
        internal static string MainForm_CantUseRequestedGeneratedNumbers {
            get {
                return ResourceManager.GetString("MainForm_CantUseRequestedGeneratedNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} se nepodařilo vytvořit..
        /// </summary>
        internal static string MainForm_CouldNotCreateTextFile {
            get {
                return ResourceManager.GetString("MainForm_CouldNotCreateTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} byl  úspěšně otestován!.
        /// </summary>
        internal static string MainForm_FileWasSuccessfulyTested {
            get {
                return ResourceManager.GetString("MainForm_FileWasSuccessfulyTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budou přepsány stávající vstupy/výstupy!.
        /// </summary>
        internal static string MainForm_InputsAndOutputsWillBeOverwriten {
            get {
                return ResourceManager.GetString("MainForm_InputsAndOutputsWillBeOverwriten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ve zvolené složce nejsou žádné zdrojové kódy!.
        /// </summary>
        internal static string MainForm_NoSourceCodesInSelectedDirectory {
            get {
                return ResourceManager.GetString("MainForm_NoSourceCodesInSelectedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není co exportovat. Nejprve musíte přidat alespoň jeden vstup/výstup..
        /// </summary>
        internal static string MainForm_NothingToExport {
            get {
                return ResourceManager.GetString("MainForm_NothingToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet souborů: {0}.
        /// </summary>
        internal static string MainForm_NumberOfFiles {
            get {
                return ResourceManager.GetString("MainForm_NumberOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahajuji testy!.
        /// </summary>
        internal static string MainForm_StartingTests {
            get {
                return ResourceManager.GetString("MainForm_StartingTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správně: {0} | Špatně: {1} | Čas: {2}| {3}.
        /// </summary>
        internal static string MainForm_TestResultLine {
            get {
                return ResourceManager.GetString("MainForm_TestResultLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejdříve musíte zvolit adresář obsahující zdrojové kódy..
        /// </summary>
        internal static string MainForm_YouHaveToSelectDirectoryWithSourceCodes {
            get {
                return ResourceManager.GetString("MainForm_YouHaveToSelectDirectoryWithSourceCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musíte nejdříve vytvořit testovací protokol!.
        /// </summary>
        internal static string MainForm_YouNeedToCreateTestProtocolFirst {
            get {
                return ResourceManager.GetString("MainForm_YouNeedToCreateTestProtocolFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno souboru.
        /// </summary>
        internal static string NameOfFile {
            get {
                return ResourceManager.GetString("NameOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není co opakovat..
        /// </summary>
        internal static string NothingToRepeat {
            get {
                return ResourceManager.GetString("NothingToRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyly nalezeny žádné platné soubory..
        /// </summary>
        internal static string NoValidFilesFound {
            get {
                return ResourceManager.GetString("NoValidFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výstup.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: počet čísel splňujících podmínky.
        /// </summary>
        internal static string OutputCountOfNumbersMatchingConditions {
            get {
                return ResourceManager.GetString("OutputCountOfNumbersMatchingConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podmínka není validní..
        /// </summary>
        internal static string OutputCountOfNumbersMatchingConditions_InvalidCondition {
            get {
                return ResourceManager.GetString("OutputCountOfNumbersMatchingConditions_InvalidCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadovaný počet čísel není možný..
        /// </summary>
        internal static string OutputCountOfNumbersMatchingConditions_RequestedNumberOfNumbersIsNotPOssible {
            get {
                return ResourceManager.GetString("OutputCountOfNumbersMatchingConditions_RequestedNumberOfNumbersIsNotPOssible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato podmínka již existuje..
        /// </summary>
        internal static string OutputCountOfNumbersMatchingConditions_ThisConditionAllreadyExists {
            get {
                return ResourceManager.GetString("OutputCountOfNumbersMatchingConditions_ThisConditionAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musíte zvolit kterou podmínku chcete vymazat..
        /// </summary>
        internal static string OutputCountOfNumbersMatchingConditions_YouHaveToSelectConditionForDeletion {
            get {
                return ResourceManager.GetString("OutputCountOfNumbersMatchingConditions_YouHaveToSelectConditionForDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: číslo.
        /// </summary>
        internal static string OutputNumber {
            get {
                return ResourceManager.GetString("OutputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: číslo založené na vygenerovaném číslu.
        /// </summary>
        internal static string OutputNumberBasedOnRandomInput {
            get {
                return ResourceManager.GetString("OutputNumberBasedOnRandomInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matematický příklad nemá správný formát! 
        ///Pokud si přejete pokračovat objekt bude smazán..
        /// </summary>
        internal static string OutputNumberBasedOnRandomInput_InvalidFormatOfMath {
            get {
                return ResourceManager.GetString("OutputNumberBasedOnRandomInput_InvalidFormatOfMath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musíte zadat platný matematický příklad..
        /// </summary>
        internal static string OutputNumberBasedOnRandomInput_YouHaveToEnterValidMath {
            get {
                return ResourceManager.GetString("OutputNumberBasedOnRandomInput_YouHaveToEnterValidMath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: číslo splňující podmínky.
        /// </summary>
        internal static string OutputNumberMatchingConditions {
            get {
                return ResourceManager.GetString("OutputNumberMatchingConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato podmínka již existuje..
        /// </summary>
        internal static string OutputNumberMatchingConditions_ThisConditionAllreadyExists {
            get {
                return ResourceManager.GetString("OutputNumberMatchingConditions_ThisConditionAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝSTUP: text.
        /// </summary>
        internal static string OutputString {
            get {
                return ResourceManager.GetString("OutputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASTAVENÍ: odchylka.
        /// </summary>
        internal static string SettingsDeviation {
            get {
                return ResourceManager.GetString("SettingsDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odchylka je již nastavena!.
        /// </summary>
        internal static string SettingsDeviation_DeviationIsAllreadySet {
            get {
                return ResourceManager.GetString("SettingsDeviation_DeviationIsAllreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASTAVENÍ: zakázaný příkaz.
        /// </summary>
        internal static string SettingsProhibitedCommand {
            get {
                return ResourceManager.GetString("SettingsProhibitedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASTAVENÍ: vyžadovaný příkaz.
        /// </summary>
        internal static string SettingsRequiedCommand {
            get {
                return ResourceManager.GetString("SettingsRequiedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASTAVENÍ: Spouštěcí parametry.
        /// </summary>
        internal static string SettingsStartupArguments {
            get {
                return ResourceManager.GetString("SettingsStartupArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouštěcí parametry jsou již nastaveny..
        /// </summary>
        internal static string SettingsStartupArguments_StartupArgumentsAreAllreadySet {
            get {
                return ResourceManager.GetString("SettingsStartupArguments_StartupArgumentsAreAllreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASTAVENÍ: maximální čas pro běh programu.
        /// </summary>
        internal static string SettingsTimeout {
            get {
                return ResourceManager.GetString("SettingsTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout je již nastaven!.
        /// </summary>
        internal static string SettingsTimeout_TimeoutAllreadySet {
            get {
                return ResourceManager.GetString("SettingsTimeout_TimeoutAllreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezeno několik souborů s metodou Main!.
        /// </summary>
        internal static string SourceCodeJava_MultipleFilesWithMainFound {
            get {
                return ResourceManager.GetString("SourceCodeJava_MultipleFilesWithMainFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezen soubor s metodou Main!.
        /// </summary>
        internal static string SourceCodeJava_NoFileWithMainFound {
            get {
                return ResourceManager.GetString("SourceCodeJava_NoFileWithMainFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Složka obsahuje samostatné soubory i skupiny souborů.
        ///Buď odstraňte složky se skupinami souborů nebo samostatné soubory..
        /// </summary>
        internal static string SourceCodes_JavaSingleMultiMismatch {
            get {
                return ResourceManager.GetString("SourceCodes_JavaSingleMultiMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nopodporovaný typ souboru..
        /// </summary>
        internal static string SourceCodes_UnsuportedFileExtension {
            get {
                return ResourceManager.GetString("SourceCodes_UnsuportedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikace nebyla ukončena před timeoutem ({0}s)\n.
        /// </summary>
        internal static string Test_AppDidNotEndedBeforeTimeout {
            get {
                return ResourceManager.GetString("Test_AppDidNotEndedBeforeTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompilátor nebyl nalezen! \n {0}.
        /// </summary>
        internal static string Test_CompilatorNotFound {
            get {
                return ResourceManager.GetString("Test_CompilatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java nebyla nalezena!\n{0}.
        /// </summary>
        internal static string Test_JavaNotFound {
            get {
                return ResourceManager.GetString("Test_JavaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezen nepovolený příkaz: {0}.
        /// </summary>
        internal static string Test_ProhibitedCommandFound {
            get {
                return ResourceManager.GetString("Test_ProhibitedCommandFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezen vyžadovaný příkaz: {0}.
        /// </summary>
        internal static string Test_RequiedCommandWasNotFound {
            get {
                return ResourceManager.GetString("Test_RequiedCommandWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testuje se.
        /// </summary>
        internal static string TestInProgress {
            get {
                return ResourceManager.GetString("TestInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodporovaný typ zdrojového souboru!.
        /// </summary>
        internal static string TestManager_UnsuportedTypeOfSourceCode {
            get {
                return ResourceManager.GetString("TestManager_UnsuportedTypeOfSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&quot; nelze převést na číslo..
        /// </summary>
        internal static string TestResult_CannotConvertNumber {
            get {
                return ResourceManager.GetString("TestResult_CannotConvertNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matematický příklad obsahuje neexistující neznámou..
        /// </summary>
        internal static string Validator_UnknownVariable {
            get {
                return ResourceManager.GetString("Validator_UnknownVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornění.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Během importu se vyskytla chyba!.
        /// </summary>
        internal static string XmlManager_ImportFailed {
            get {
                return ResourceManager.GetString("XmlManager_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}není podporován a nebyl importován..
        /// </summary>
        internal static string XmlManager_InvalidDataImportFail {
            get {
                return ResourceManager.GetString("XmlManager_InvalidDataImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolený XML soubor není podporován..
        /// </summary>
        internal static string XmlManager_UnsuportedXmlFile {
            get {
                return ResourceManager.GetString("XmlManager_UnsuportedXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na čtení {0} nemáte oprávnění!.
        /// </summary>
        internal static string YouDontHavePermisionsToReadFile {
            get {
                return ResourceManager.GetString("YouDontHavePermisionsToReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musíte vybrat soubor!.
        /// </summary>
        internal static string YouHaveToSelectFile {
            get {
                return ResourceManager.GetString("YouHaveToSelectFile", resourceCulture);
            }
        }
    }
}
